### ISSUE TITLE
Use time as x axis

### ISSUE THREAD

**Issue by Siggenx** [copperwire/SIMS#9]
I just added a data file where time is added. The file import seems to work fine until I try to create these with bokeh. It seems like it tries to add both the depth and the time as the time axis. For this file, i only care about the time since the depth is inaccurate. This is the error I get:

``` Python


filename = ["Data_files/depth_profile/time_x_axis.dp_rpc_asc"]
test = interactive_plotting(filename)
test.data_generation()
test.plotting()
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-29-bb22b406478f> in <module>()
      2 test = interactive_plotting(filename)
      3 test.data_generation()
----> 4 test.plotting()

/home/sigbjorn/SIMS/interactive_plotting.py in plotting(self)
     73                                 for unit in y_axis_units:
     74                                         if not unit == y_axis_units[0]:
---> 75                                                 figure_obj.extra_y_ranges =  {"foo": Range1d(start = np.amin(y_data), end = np.amax(y_data))}
     76                                                 figure_obj.add_layout(LogAxis(y_range_name = "foo", axis_label = unit), "right")
     77                                                 break

UnboundLocalError: local variable 'y_data' referenced before assignment
```

**Comment by copperwire** [comment]
This is a problem I've yet to solve with different configurations of units. I'm not certain what kind of logic can be applied to determine whether the unit on the x-axis is time or length. 

I've considered using the magnitude of the first element to determine what configuration of units to be used - but that might be unreliable.

**Comment by copperwire** [comment]
Should be working now (and has been for a little while, sorry)!
